/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5JLE8lmuFC5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"

export default function resources() {
  return (
    (<div className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div
          className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Resources for Your Success</h1>
            <p
              className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Discover the wide range of resources available to support your academic and personal growth at our
              college.
            </p>
          </div>
        </div>
        <div
          className="mx-auto grid grid-cols-1 gap-8 py-12 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-primary p-3 text-primary-foreground">
                <LibraryIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Campus Library</h3>
                <p className="text-muted-foreground">
                  Explore our extensive collection of books, journals, and digital resources to support your academic
                  research and learning.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-secondary p-3 text-secondary-foreground">
                <BriefcaseIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Career Center</h3>
                <p className="text-muted-foreground">
                  Get personalized career guidance, access job postings, and prepare for interviews to kickstart your
                  professional journey.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-muted p-3 text-muted-foreground">
                <HeartIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Mental Health Services</h3>
                <p className="text-muted-foreground">
                  Prioritize your well-being with access to counseling, support groups, and wellness workshops to help
                  you thrive.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-accent p-3 text-accent-foreground">
                <UsersIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Student Clubs</h3>
                <p className="text-muted-foreground">
                  Explore a wide range of student clubs and organizations to connect with like-minded peers, develop new
                  skills, and enrich your college experience.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-primary p-3 text-primary-foreground">
                <LaptopIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">IT Support</h3>
                <p className="text-muted-foreground">
                  Get technical assistance with your devices, software, and network connectivity to ensure a seamless
                  academic experience.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-secondary p-3 text-secondary-foreground">
                <AccessibilityIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Disability Services</h3>
                <p className="text-muted-foreground">
                  Receive personalized accommodations and support to ensure your academic success, regardless of your
                  abilities or needs.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-muted p-3 text-muted-foreground">
                <GraduationCapIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Academic Advising</h3>
                <p className="text-muted-foreground">
                  Meet with our dedicated academic advisors to plan your course of study, explore majors, and ensure you
                  stay on track to graduate.
                </p>
              </div>
            </CardContent>
          </Card>
          <Card className="group">
            <CardContent className="flex flex-col items-center justify-center gap-4 p-6">
              <div className="rounded-full bg-accent p-3 text-accent-foreground">
                <DollarSignIcon className="h-8 w-8" />
              </div>
              <div className="text-center">
                <h3 className="text-lg font-semibold">Financial Aid</h3>
                <p className="text-muted-foreground">
                  Explore various financial aid options, including scholarships, grants, and loans, to make your college
                  education more accessible.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>)
  );
}

function AccessibilityIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>)
  );
}


function DollarSignIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>)
  );
}


function GraduationCapIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>)
  );
}


function HeartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>)
  );
}


function LaptopIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>)
  );
}


function LibraryIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m16 6 4 14" />
      <path d="M12 6v14" />
      <path d="M8 8v12" />
      <path d="M4 4v16" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
