/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2Jn5YmGyORL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Serif_Display } from 'next/font/google'
import { Prata } from 'next/font/google'

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"

export function HomepageMainBody() {
  return (
    (<div className="flex flex-col min-h-dvh">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <UniversityIcon className="w-8 h-8" />
          <h1 className="text-2xl font-bold">Acme University</h1>
        </div>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Academics
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Admissions
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Campus Life
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            News
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="outline" size="icon" className="md:hidden">
          <MenuIcon className="w-6 h-6" />
          <span className="sr-only">Toggle navigation</span>
        </Button>
      </header>
      <main className="flex-1">
        <Carousel className="w-full max-w-7xl mx-auto py-12 md:py-16 lg:py-20">
          <CarouselContent>
            <CarouselItem>
              <div className="flex flex-col md:flex-row items-center gap-8 px-4 md:px-0">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="Carousel Image"
                  className="rounded-lg w-full md:w-1/2 object-cover" />
                <div className="space-y-4 text-center md:text-left">
                  <h2 className="text-3xl font-bold">Upcoming Campus Event</h2>
                  <p className="text-muted-foreground">
                    Join us for our annual campus event featuring speakers, workshops, and more.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="flex flex-col md:flex-row items-center gap-8 px-4 md:px-0">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="Carousel Image"
                  className="rounded-lg w-full md:w-1/2 object-cover" />
                <div className="space-y-4 text-center md:text-left">
                  <h2 className="text-3xl font-bold">New Degree Program</h2>
                  <p className="text-muted-foreground">Explore our latest degree program in Sustainable Engineering.</p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="flex flex-col md:flex-row items-center gap-8 px-4 md:px-0">
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="Carousel Image"
                  className="rounded-lg w-full md:w-1/2 object-cover" />
                <div className="space-y-4 text-center md:text-left">
                  <h2 className="text-3xl font-bold">Research Highlights</h2>
                  <p className="text-muted-foreground">Discover the latest groundbreaking research from our faculty.</p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Learn More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </div>
              </div>
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
        <section className="bg-muted py-12 md:py-16 lg:py-20">
          <div className="container max-w-7xl mx-auto px-4 md:px-6">
            <h2 className="text-3xl font-bold mb-8">Latest News</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="News Image"
                  className="rounded-t-lg w-full object-cover" />
                <CardContent className="p-6">
                  <h3 className="text-xl font-bold mb-2">Acme University Launches New Sustainability Initiative</h3>
                  <p className="text-muted-foreground mb-4">
                    Acme University is proud to announce the launch of our new sustainability initiative, aimed at
                    reducing our carbon footprint and promoting eco-friendly practices on campus.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Read More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="News Image"
                  className="rounded-t-lg w-full object-cover" />
                <CardContent className="p-6">
                  <h3 className="text-xl font-bold mb-2">Acme University Ranked Top 10 in the Nation</h3>
                  <p className="text-muted-foreground mb-4">
                    Acme University has been ranked as one of the top 10 universities in the nation, recognizing our
                    commitment to academic excellence and student success.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Read More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={600}
                  height={400}
                  alt="News Image"
                  className="rounded-t-lg w-full object-cover" />
                <CardContent className="p-6">
                  <h3 className="text-xl font-bold mb-2">Acme University Hosts Annual Alumni Homecoming</h3>
                  <p className="text-muted-foreground mb-4">
                    Join us for our annual Alumni Homecoming, a weekend filled with exciting events, reunions, and
                    celebrations for our Acme University community.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 text-primary font-medium hover:underline"
                    prefetch={false}>
                    Read More
                    <ArrowRightIcon className="w-4 h-4" />
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div
          className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">About</h3>
            <Link href="#" prefetch={false}>
              History
            </Link>
            <Link href="#" prefetch={false}>
              Mission & Values
            </Link>
            <Link href="#" prefetch={false}>
              Leadership
            </Link>
            <Link href="#" prefetch={false}>
              Accreditations
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Academics</h3>
            <Link href="#" prefetch={false}>
              Undergraduate
            </Link>
            <Link href="#" prefetch={false}>
              Graduate
            </Link>
            <Link href="#" prefetch={false}>
              Online Programs
            </Link>
            <Link href="#" prefetch={false}>
              Research
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Admissions</h3>
            <Link href="#" prefetch={false}>
              Apply
            </Link>
            <Link href="#" prefetch={false}>
              Tuition & Aid
            </Link>
            <Link href="#" prefetch={false}>
              Visit Campus
            </Link>
            <Link href="#" prefetch={false}>
              International Students
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Campus Life</h3>
            <Link href="#" prefetch={false}>
              Housing
            </Link>
            <Link href="#" prefetch={false}>
              Dining
            </Link>
            <Link href="#" prefetch={false}>
              Student Organizations
            </Link>
            <Link href="#" prefetch={false}>
              Athletics
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Library
            </Link>
            <Link href="#" prefetch={false}>
              Career Services
            </Link>
            <Link href="#" prefetch={false}>
              Counseling
            </Link>
            <Link href="#" prefetch={false}>
              Disability Services
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}

function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function UniversityIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="10" r="1" />
      <path d="M22 20V8h-4l-6-4-6 4H2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2" />
      <path d="M6 17v.01" />
      <path d="M6 13v.01" />
      <path d="M18 17v.01" />
      <path d="M18 13v.01" />
      <path d="M14 22v-5a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v5" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
