/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OKU85flKK8Z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Image from "next/image";


export default function AboutPage() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div
          className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <Image
            src="https://mastercardfdn.org/wp-content/themes/mastercard-foundation/assets/img/mc-logo-black.svg"
            alt="KNUST Mastercard Foundation Logo"
            width={32}
            height={32}
            className="h-16 w-16 mx-auto"
          />
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl ">Mastercard Foundation</h1>
            <p
              className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              The Mastercard Foundation is a private charitable foundation that advances financial inclusion and
              inclusive growth around the world. We believe that all people should have the opportunity to learn,
              prosper, and contribute to their communities.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-red-700">Our Mission</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Empowering People Through Financial Inclusion
              </h2>
              <p
                className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our mission is to advance financial inclusion and inclusive growth around the world. We believe that all
                people should have the opportunity to learn, prosper, and contribute to their communities.
              </p>
            </div>
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-red-700">Our Core Values</div>
              <ul className="grid gap-4">
                <li className="flex items-start gap-4">
                  <CheckIcon className="mt-1 h-5 w-5 flex-shrink-0 text-primary" />
                  <div>
                    <h3 className="text-lg font-bold text-amber-500">Empowerment</h3>
                    <p className="text-muted-foreground">
                      We believe in empowering people to take control of their financial futures and contribute to their
                      communities.
                    </p>
                  </div>
                </li>
                <li className="flex items-start gap-4">
                  <CheckIcon className="mt-1 h-5 w-5 flex-shrink-0 text-primary" />
                  <div>
                    <h3 className="text-lg font-bold text-amber-500">Collaboration</h3>
                    <p className="text-muted-foreground">
                      We work closely with our partners and communities to understand their needs and deliver tailored
                      solutions.
                    </p>
                  </div>
                </li>
                <li className="flex items-start gap-4">
                  <CheckIcon className="mt-1 h-5 w-5 flex-shrink-0 text-primary" />
                  <div>
                    <h3 className="text-lg font-bold text-amber-500">Impact</h3>
                    <p className="text-muted-foreground">
                      We are committed to creating lasting, positive change in the lives of the people and communities
                      we serve.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-red-700">Our Team</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Meet the Mastercard Foundation Team
            </h2>
            <p
              className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Our team of experts is dedicated to advancing financial inclusion and creating positive change around the
              world.
            </p>
          </div>
          <div
            className="mx-auto grid max-w-5xl grid-cols-1 gap-8 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
            <div className="flex flex-col items-center justify-center space-y-4">
              <Avatar className="h-24 w-24">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>RR</AvatarFallback>
              </Avatar>
              <div className="text-center">
                <h3 className="text-lg font-bold">Reeta Roy</h3>
                <p className="text-muted-foreground">President and CEO</p>
                <p className="text-sm text-muted-foreground">
                  Reeta Roy is the President and CEO of the Mastercard Foundation. She has over 30 years of experience
                  in the international development and philanthropic sectors, and is passionate about creating
                  opportunities for people around the world.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center space-y-4">
              <Avatar className="h-24 w-24">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>ZY</AvatarFallback>
              </Avatar>
              <div className="text-center">
                <h3 className="text-lg font-bold">Zouera Youssoufou</h3>
                <p className="text-muted-foreground">Managing Director, Africa</p>
                <p className="text-sm text-muted-foreground">
                  Zouera Youssoufou is the Managing Director for Africa at the Mastercard Foundation. She has extensive
                  experience in international development and is committed to driving financial inclusion and inclusive
                  growth across the continent.
                </p>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center space-y-4">
              <Avatar className="h-24 w-24">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>AM</AvatarFallback>
              </Avatar>
              <div className="text-center">
                <h3 className="text-lg font-bold">Ann Miles</h3>
                <p className="text-muted-foreground">Director, Financial Inclusion</p>
                <p className="text-sm text-muted-foreground">
                  Ann Miles is the Director of Financial Inclusion at the Mastercard Foundation. She has a deep
                  understanding of the financial inclusion landscape and is responsible for developing and implementing
                  strategies to expand access to financial services around the world.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
